spring:
  datasource:
    url: jdbc:mysql://localhost:3306/face_recognition?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  config:
    import: nacos:application.yml,file:${user.dir}/config/config.yml
  security:
    enabled: false
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: users
          uri:  lb://users  # lb表示负载均衡
          predicates:
            - Path=/users/**
#          filters:
#            - auth
        - id: login
          uri:  lb://login
          predicates:
            - Path=/in/**
#          filters:
#            - auth
        - id: voice-synthesis
          uri:  lb://voice-synthesis
          predicates:
            - Path=/voice/**
#          filters:
#            - auth
        - id: recognition
          uri:  lb://recognition
          predicates:
            - Path=/recognition/**
#          filters:
#            - auth
#        - id: AI
#          uri:  lb://AI
#          predicates:
#            - Path=/ai/**
#
#        - id: tag
#          uri:  lb://tag
#          predicates:
#              - Path=/system/tag/**
##          filters:
##            - auth
#        - id: learning
#          uri:  lb://learning
#          predicates:
#            - Path=/learning/**
##          filters:
##            - auth
#        - id: activity
#          uri:  lb://activity
#          predicates:
#            - Path=/api/activity/**
##          filters:
##            - auth
#        - id: advertisement
#          uri:  lb://advertisement
#          predicates:
#            - Path=/api/advertisement/**
##          filters:
##            - auth
#        - id: forum
#          uri:  lb://forum
#          predicates:
#            - Path=/api/forum/**
##          filters:
##            - auth
#        - id: event
#          uri:  lb://event
#          predicates:
#            - Path=/api/event/**
#          filters:
#            - auth
hm:
  auth:
    excludePaths:
      - /in/**
      - /users/**
      - /search/**
      - /system/**
      - /recognition/detect

# 使用config.yml中的端口配置
server:
  port: ${gateway.port:8089}
  allowedUrl: ${gateway.host}
logging:
  level:
    org.springframework.security: TRACE
