spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  security:
    enabled: false
  application:
    name: chat
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
mybatis:
  configuration:
    type-handlers:
      - org.apache.ibatis.type.EnumOrdinalTypeHandler

logging:
  level:
    org.springframework.security: TRACE
    com.homework.common.feign.BoChaClient: DEBUG
    feign.Logger: DEBUG